# Generated by Django 4.1.1 on 2022-11-03 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesstore',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=0.0), django.core.validators.MaxValueValidator(limit_value=1000000.0)]),
        ),
    ]
