# Generated by Django 4.1.1 on 2022-11-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesstore',
            name='category',
            field=models.CharField(choices=[('Utilities', (('electricity', 'Electricity'), ('water', 'Water'))), ('tax', ' Tax'), ('lease', 'Lease')], max_length=20),
        ),
    ]
